BEGIN;

DROP TABLE IF EXISTS course;

CREATE TABLE course
(
	id SERIAL PRIMARY KEY,
	url VARCHAR(255) NOT NULL,
	title VARCHAR(255) NOT NULL,
	image VARCHAR(255),
	rating REAL DEFAULT 0,
	reviews INTEGER DEFAULT 0,
	description TEXT,
	category INTEGER[],
	date DATE
);

COMMIT;
