const catalog = [
  {
    id: 0,
    name: 'udemy',
    sub: [
      {
        id: 1,
        name: 'Development',
        value: 288,
        sub: [
          { id: 2, name: 'Web Development', value: 8 },
          { id: 3, name: 'Data Science', value: 558 },
          { id: 4, name: 'Mobile Development', value: 10 },
          { id: 5, name: 'Programming Languages', value: 12 },
          { id: 6, name: 'Game Development', value: 14 },
          { id: 7, name: 'Database Design & Development', value: 16 },
          { id: 8, name: 'Software Testing', value: 18 },
          { id: 9, name: 'Software Engineering', value: 20 },
          { id: 10, name: 'Development Tools', value: 362 },
          { id: 11, name: 'No-Code Development', value: 575 },
        ],
      },
      {
        id: 12,
        name: 'Business',
        value: 268,
        sub: [
          { id: 13, name: 'Entrepreneurship', value: 26 },
          { id: 14, name: 'Communications', value: 28 },
          { id: 15, name: 'Management', value: 30 },
          { id: 16, name: 'Sales', value: 32 },
          { id: 17, name: 'Business Strategy', value: 34 },
          { id: 18, name: 'Operations', value: 36 },
          { id: 19, name: 'Project Management', value: 38 },
          { id: 20, name: 'Business Law', value: 40 },
          { id: 21, name: 'Business Analytics & Intelligence', value: 44 },
          { id: 22, name: 'Human Resources', value: 48 },
          { id: 23, name: 'Industry', value: 50 },
          { id: 24, name: 'E-Commerce', value: 354 },
          { id: 25, name: 'Media', value: 52 },
          { id: 26, name: 'Real Estate', value: 58 },
          { id: 27, name: 'Other Business', value: 60 },
        ],
      },
      {
        id: 28,
        name: 'Finance & Accounting',
        value: 328,
        sub: [
          { id: 29, name: 'Accounting & Bookkeeping', value: 530 },
          { id: 30, name: 'Compliance', value: 532 },
          { id: 31, name: 'Cryptocurrency & Blockchain', value: 534 },
          { id: 32, name: 'Economics', value: 536 },
          { id: 33, name: 'Finance', value: 540 },
          { id: 34, name: 'Finance Cert & Exam Prep', value: 542 },
          { id: 35, name: 'Financial Modeling & Analysis', value: 544 },
          { id: 36, name: 'Investing & Trading', value: 546 },
          { id: 37, name: 'Money Management Tools', value: 548 },
          { id: 38, name: 'Taxes', value: 550 },
          { id: 39, name: 'Other Finance & Accounting', value: 552 },
        ],
      },
      {
        id: 40,
        name: 'IT & Software',
        value: 294,
        sub: [
          { id: 41, name: 'IT Certification', value: 132 },
          { id: 42, name: 'Network & Security', value: 134 },
          { id: 43, name: 'Hardware', value: 136 },
          { id: 44, name: 'Operating Systems', value: 138 },
          { id: 45, name: 'Other IT & Software', value: 140 },
        ],
      },
      {
        id: 46,
        name: 'Office Productivity',
        value: 292,
        sub: [
          { id: 47, name: 'Microsoft', value: 96 },
          { id: 48, name: 'Apple', value: 98 },
          { id: 49, name: 'Google', value: 100 },
          { id: 50, name: 'SAP', value: 102 },
          { id: 51, name: 'Oracle', value: 106 },
          { id: 52, name: 'Other Office Productivity', value: 108 },
        ],
      },
      {
        id: 53,
        name: 'Personal Development',
        value: 296,
        sub: [
          { id: 54, name: 'Personal Transformation', value: 142 },
          { id: 55, name: 'Personal Productivity', value: 144 },
          { id: 56, name: 'Leadership', value: 146 },
          { id: 57, name: 'Career Development', value: 150 },
          { id: 58, name: 'Parenting & Relationships', value: 152 },
          { id: 59, name: 'Happiness', value: 156 },
          { id: 60, name: 'Esoteric Practices', value: 577 },
          { id: 61, name: 'Religion & Spirituality', value: 158 },
          { id: 62, name: 'Personal Brand Building', value: 160 },
          { id: 63, name: 'Creativity', value: 164 },
          { id: 64, name: 'Influence', value: 166 },
          { id: 65, name: 'Self Esteem & Confidence', value: 168 },
          { id: 66, name: 'Stress Management', value: 170 },
          { id: 67, name: 'Memory & Study Skills', value: 172 },
          { id: 68, name: 'Motivation', value: 176 },
          { id: 69, name: 'Other Personal Development', value: 178 },
        ],
      },
      {
        id: 70,
        name: 'Design',
        value: 269,
        sub: [
          { id: 71, name: 'Web Design', value: 6 },
          { id: 72, name: 'Graphic Design & Illustration', value: 110 },
          { id: 73, name: 'Design Tools', value: 112 },
          { id: 74, name: 'User Experience Design', value: 114 },
          { id: 75, name: 'Game Design', value: 116 },
          { id: 76, name: 'Design Thinking', value: 118 },
          { id: 77, name: '3D & Animation', value: 120 },
          { id: 78, name: 'Fashion Design', value: 122 },
          { id: 79, name: 'Architectural Design', value: 124 },
          { id: 80, name: 'Interior Design', value: 128 },
          { id: 81, name: 'Other Design', value: 130 },
        ],
      },
      {
        id: 82,
        name: 'Marketing',
        value: 290,
        sub: [
          { id: 83, name: 'Digital Marketing', value: 62 },
          { id: 84, name: 'Search Engine Optimization', value: 64 },
          { id: 85, name: 'Social Media Marketing', value: 66 },
          { id: 86, name: 'Branding', value: 68 },
          { id: 87, name: 'Marketing Fundamentals', value: 70 },
          { id: 88, name: 'Marketing Analytics & Automation', value: 72 },
          { id: 89, name: 'Public Relations', value: 74 },
          { id: 90, name: 'Advertising', value: 76 },
          { id: 91, name: 'Video & Mobile Marketing', value: 78 },
          { id: 92, name: 'Content Marketing', value: 80 },
          { id: 93, name: 'Growth Hacking', value: 86 },
          { id: 94, name: 'Affiliate Marketing', value: 88 },
          { id: 95, name: 'Product Marketing', value: 90 },
          { id: 96, name: 'Other Marketing', value: 94 },
        ],
      },
      {
        id: 97,
        name: 'Lifestyle',
        value: 274,
        sub: [
          { id: 98, name: 'Arts & Crafts', value: 180 },
          { id: 99, name: 'Beauty & Makeup', value: 184 },
          { id: 100, name: 'Esoteric Practices', value: 577 },
          { id: 101, name: 'Food & Beverage', value: 182 },
          { id: 102, name: 'Gaming', value: 188 },
          { id: 103, name: 'Home Improvement', value: 190 },
          { id: 104, name: 'Pet Care & Training', value: 192 },
          { id: 105, name: 'Travel', value: 186 },
          { id: 106, name: 'Other Lifestyle', value: 194 },
        ],
      },
      {
        id: 107,
        name: 'Photography & Video',
        value: 273,
        sub: [
          { id: 108, name: 'Digital Photography', value: 370 },
          { id: 109, name: 'Photography', value: 196 },
          { id: 110, name: 'Portrait Photography', value: 204 },
          { id: 111, name: 'Photography Tools', value: 198 },
          { id: 112, name: 'Commercial Photography', value: 208 },
          { id: 113, name: 'Video Design', value: 218 },
          { id: 114, name: 'Other Photography & Video', value: 220 },
        ],
      },
      {
        id: 115,
        name: 'Health & Fitness',
        value: 276,
        sub: [
          { id: 116, name: 'Fitness', value: 222 },
          { id: 117, name: 'General Health', value: 224 },
          { id: 118, name: 'Sports', value: 226 },
          { id: 119, name: 'Nutrition', value: 228 },
          { id: 120, name: 'Yoga', value: 230 },
          { id: 121, name: 'Mental Health', value: 232 },
          { id: 122, name: 'Dieting', value: 234 },
          { id: 123, name: 'Self Defense', value: 236 },
          { id: 124, name: 'Safety & First Aid', value: 238 },
          { id: 125, name: 'Dance', value: 240 },
          { id: 126, name: 'Meditation', value: 242 },
          { id: 127, name: 'Other Health & Fitness', value: 244 },
        ],
      },
      {
        id: 128,
        name: 'Music',
        value: 278,
        sub: [
          { id: 129, name: 'Instruments', value: 296 },
          { id: 130, name: 'Music Production', value: 298 },
          { id: 131, name: 'Music Fundamentals', value: 300 },
          { id: 132, name: 'Vocal', value: 302 },
          { id: 133, name: 'Music Techniques', value: 304 },
          { id: 134, name: 'Music Software', value: 306 },
          { id: 135, name: 'Other Music', value: 308 },
        ],
      },
      {
        id: 136,
        name: 'Teaching & Academics',
        value: 300,
        sub: [
          { id: 137, name: 'Engineering', value: 366 },
          { id: 138, name: 'Humanities', value: 380 },
          { id: 139, name: 'Math', value: 310 },
          { id: 140, name: 'Science', value: 312 },
          { id: 141, name: 'Online Education', value: 523 },
          { id: 142, name: 'Social Science', value: 376 },
          { id: 143, name: 'Language', value: 521 },
          { id: 144, name: 'Teacher Training', value: 527 },
          { id: 145, name: 'Test Prep', value: 529 },
          { id: 146, name: 'Other Teaching & Academics', value: 525 },
        ],
      },
    ],
  },
  {
    id: 147,
    name: 'coursera',
    sub: [
      {
        id: 148,
        name: 'arts-and-humanities',
        sub: [
          { id: 149, name: 'history' },
          { id: 150, name: 'music-and-art' },
          { id: 151, name: 'philosophy' },
        ],
      },
      {
        id: 152,
        name: 'business',
        sub: [
          { id: 153, name: 'leadership-and-management' },
          { id: 154, name: 'finance' },
          { id: 155, name: 'marketing' },
          { id: 156, name: 'entrepreneurship' },
          { id: 157, name: 'business-essentials' },
          { id: 158, name: 'business-strategy' },
        ],
      },
      {
        id: 159,
        name: 'computer-science',
        sub: [
          { id: 160, name: 'software-development' },
          { id: 161, name: 'mobile-and-web-development' },
          { id: 162, name: 'algorithms' },
          { id: 163, name: 'computer-security-and-networks' },
          { id: 164, name: 'design-and-product' },
        ],
      },
      {
        id: 165,
        name: 'data-science',
        sub: [
          { id: 166, name: 'data-analysis' },
          { id: 167, name: 'machine-learning' },
          { id: 168, name: 'probability-and-statistics' },
        ],
      },
      {
        id: 169,
        name: 'information-technology',
        sub: [
          { id: 170, name: 'cloud-computing' },
          { id: 171, name: 'security' },
          { id: 172, name: 'data-management' },
          { id: 173, name: 'networking' },
          { id: 174, name: 'support-and-operations' },
        ],
      },
      {
        id: 175,
        name: 'health',
        sub: [
          { id: 176, name: 'animal-health' },
          { id: 177, name: 'basic-science' },
          { id: 178, name: 'health-informatics' },
          { id: 179, name: 'healthcare-management' },
          { id: 180, name: 'nutrition' },
          { id: 181, name: 'patient-care' },
          { id: 182, name: 'public-health' },
          { id: 183, name: 'research' },
          { id: 184, name: 'psychology' },
        ],
      },
      { id: 185, name: 'math-and-logic', sub: [] },
      { id: 186, name: 'personal-development', sub: [] },
      {
        id: 187,
        name: 'physical-science-and-engineering',
        sub: [
          { id: 188, name: 'electrical-engineering' },
          { id: 189, name: 'mechanical-engineering' },
          { id: 190, name: 'chemistry' },
          { id: 191, name: 'environmental-science-and-sustainability' },
          { id: 192, name: 'physics-and-astronomy' },
          { id: 193, name: 'research-methods' },
        ],
      },
      {
        id: 194,
        name: 'social-sciences',
        sub: [
          { id: 195, name: 'economics' },
          { id: 196, name: 'education' },
          { id: 197, name: 'governance-and-society' },
          { id: 198, name: 'law' },
        ],
      },
      {
        id: 199,
        name: 'language-learning',
        sub: [
          { id: 200, name: 'learning-english' },
          { id: 201, name: 'other-languages' },
        ],
      },
    ],
  },
  {
    id: 202,
    name: 'edx',
    sub: [
      { id: 203, name: 'Business & Management' },
      { id: 204, name: 'Computer Science' },
      { id: 205, name: 'Engineering' },
      { id: 206, name: 'Social Sciences' },
      { id: 207, name: 'Data Analysis & Statistics' },
      { id: 208, name: 'Economics & Finance' },
      { id: 209, name: 'Humanities' },
      { id: 210, name: 'Science' },
      { id: 211, name: 'Biology & Life Sciences' },
      { id: 212, name: 'Communication' },
      { id: 213, name: 'Medicine' },
      { id: 214, name: 'Environmental Studies' },
      { id: 215, name: 'Physics' },
      { id: 216, name: 'Art & Culture' },
      { id: 217, name: 'Health & Safety' },
      { id: 218, name: 'History' },
      { id: 219, name: 'Math' },
      { id: 220, name: 'Education & Teacher Training' },
      { id: 221, name: 'Design' },
      { id: 222, name: 'Energy & Earth Sciences' },
      { id: 223, name: 'Philosophy & Ethics' },
      { id: 224, name: 'Law' },
      { id: 225, name: 'Electronics' },
      { id: 226, name: 'Language' },
      { id: 227, name: 'Chemistry' },
      { id: 228, name: 'Literature' },
      { id: 229, name: 'Food & Nutrition' },
      { id: 230, name: 'Architecture' },
      { id: 231, name: 'Ethics' },
      { id: 232, name: 'Music' },
      { id: 233, name: 'Philanthropy' },
    ],
  },
  {
    id: 234,
    name: 'alison',
    sub: [
      { id: 235, name: 'business' },
      { id: 236, name: 'education' },
      { id: 237, name: 'engineering' },
      { id: 238, name: 'health' },
      { id: 239, name: 'it' },
      { id: 240, name: 'language' },
      { id: 241, name: 'management' },
      { id: 242, name: 'marketing' },
      { id: 243, name: 'personal-development' },
    ],
  },
  {
    id: 244,
    name: 'futurelearn',
    sub: [
      { id: 245, name: 'Business & Management', value: 8 },
      { id: 246, name: 'Creative Arts & Media', value: 9 },
      { id: 247, name: 'Nature & Environment', value: 10 },
      { id: 248, name: 'Politics & Society', value: 11 },
      { id: 249, name: 'Literature', value: 12 },
      { id: 250, name: 'Healthcare & Medicine', value: 13 },
      { id: 251, name: 'Science, Engineering & Maths', value: 14 },
      { id: 252, name: 'Law', value: 15 },
      { id: 253, name: 'History', value: 16 },
      { id: 254, name: 'IT & Computer Science', value: 17 },
      { id: 255, name: 'Teaching', value: 18 },
      { id: 256, name: 'Language', value: 19 },
      { id: 257, name: 'Study Skills', value: 21 },
      { id: 258, name: 'Psychology & Mental Health', value: 22 },
    ],
  },
];

module.exports = catalog;
